# Spring Application name
spring.application.name=backend


# Server Configuration
server.port=${SERVER_PORT:8080}

# Database Connection (PostgreSQL)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ticket_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Security Configurations
# 256-bit Hex encoded secret key for HMAC SHA-256
app.jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
# Expiration: 1 day in milliseconds (24 * 60 * 60 * 1000)
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

# OpenAPI Swagger Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
